permissions: write-all # Equivalent to default permissions plus id-token: write
name: Publish to Docker Hub
on:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
  FRONT_IMAGE_NAME: ${{ github.repository }}-frontend
  BACK_IMAGE_NAME: ${{ github.repository }}-backend
  DATABASE_IMAGE_NAME: ${{ github.repository }}-database
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: github-secrets/pulumi-tutorial-pulumi-fundamentals
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false

jobs:
  push-front-to-registry:
    name: Publish frontend image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ steps.esc-secrets.outputs.DOCKERHUB_USERNAME }}
          password: ${{ steps.esc-secrets.outputs.DOCKERHUB_TOKEN }}

      - name: Add front metadata for Docker Hub
        id: meta-front
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONT_IMAGE_NAME }}
          flavor: |
            latest=true
            

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-front.outputs.tags }}
          labels: ${{ steps.meta-front.outputs.labels }}

  push-back-to-registry:
    name: Publish backend image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ steps.esc-secrets.outputs.DOCKERHUB_USERNAME }}
          password: ${{ steps.esc-secrets.outputs.DOCKERHUB_TOKEN }}

      - name: Add back metadata for Docker Hub
        id: meta-back
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.BACK_IMAGE_NAME }}
          flavor: |
            latest=true
            

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-back.outputs.tags }}
          labels: ${{ steps.meta-back.outputs.labels }}

  push-db-to-registry:
    name: Publish database image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ steps.esc-secrets.outputs.DOCKERHUB_USERNAME }}
          password: ${{ steps.esc-secrets.outputs.DOCKERHUB_TOKEN }}

      - name: Add data metadata for Docker Hub
        id: meta-data
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.DATABASE_IMAGE_NAME }}
          flavor: |
            latest=true
            

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push database image
        uses: docker/build-push-action@v3
        with:
          context: ./data/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-data.outputs.tags }}
          labels: ${{ steps.meta-data.outputs.labels }}
